// <auto-generated />
using System;
using IcecreamMAUI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IcecreamMAUI.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.Icecream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Icecreams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "vanilla.png",
                            Name = "Vanilla Dream",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Image = "chocolate.png",
                            Name = "Chocolate Bliss",
                            Price = 7.9000000000000004
                        },
                        new
                        {
                            Id = 3,
                            Image = "strawberry.png",
                            Name = "Strawberry Swirl",
                            Price = 8.6999999999999993
                        },
                        new
                        {
                            Id = 4,
                            Image = "mango.png",
                            Name = "Mango Magic",
                            Price = 3.6400000000000001
                        },
                        new
                        {
                            Id = 5,
                            Image = "blue_berry.png",
                            Name = "Blueberry Burst",
                            Price = 9.7799999999999994
                        });
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.IcecreamOption", b =>
                {
                    b.Property<int>("IcecreamId")
                        .HasColumnType("int");

                    b.Property<string>("Flavor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Topping")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IcecreamId", "Flavor", "Topping");

                    b.ToTable("IcecreamOptions");

                    b.HasData(
                        new
                        {
                            IcecreamId = 1,
                            Flavor = "Classic Vanilla",
                            Topping = "Choco Chips"
                        },
                        new
                        {
                            IcecreamId = 2,
                            Flavor = "Dark Chocolate",
                            Topping = "Brownie Bits"
                        },
                        new
                        {
                            IcecreamId = 3,
                            Flavor = "Fresh Strawberry",
                            Topping = "Whipped Cream"
                        },
                        new
                        {
                            IcecreamId = 4,
                            Flavor = "Alphonso Mango",
                            Topping = "Honey Drizzle"
                        },
                        new
                        {
                            IcecreamId = 5,
                            Flavor = "Wild Blueberry",
                            Topping = "Sprinkles"
                        });
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CustomerAddress")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrederAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IcecreamId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Topping")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Totalprice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.IcecreamOption", b =>
                {
                    b.HasOne("IcecreamMAUI.API.Data.Entities.Icecream", "Icecream")
                        .WithMany("Options")
                        .HasForeignKey("IcecreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icecream");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("IcecreamMAUI.API.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.Icecream", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("IcecreamMAUI.API.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
